package com.example.Student_Library_Management_System.Models;

import com.example.Student_Library_Management_System.Enums.CardStatus;
import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Entity
@Table(name="card")
public class Card {

    // Plan is to save this card in Db.
    // Before saving, I have to set its attributes : Rule no. 1

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) /// It is now autogenerated.
    private int id;

    @CreationTimestamp  //Auto  timeStamp the time when an entry is created, and it is autogenerated
    private Date createOn;


    @UpdateTimestamp   // Sets time when an entry is updated ,and autogenerated.
    private Date updatedOn;

    @Enumerated(value = EnumType.STRING)
    private CardStatus cardStatus; // Set this attribute

    @OneToOne   // unidirectional mapping
    @JoinColumn
    private Student studentVariableName;  // This variable is used in parent class

    @OneToMany(mappedBy = "card",cascade = CascadeType.ALL)
    List<Book>bookIssued=new ArrayList<>();

    @OneToMany(mappedBy = "card",cascade = CascadeType.ALL)
    List<Transactions>listOfTransactions=new ArrayList<>();




    public Card() {
    }

    public List<Book> getBookIssued() {
        return bookIssued;
    }

    public void setBookIssued(List<Book> bookIssued) {
        this.bookIssued = bookIssued;
    }

    public List<Transactions> getListOfTransactions() {
        return listOfTransactions;
    }

    public void setListOfTransactions(List<Transactions> listOfTransactions) {
        this.listOfTransactions = listOfTransactions;
    }

    public CardStatus getCardStatus() {
        return cardStatus;
    }

    public void setCardStatus(CardStatus cardStatus) {
        this.cardStatus = cardStatus;
    }

    public Student getStudentVariableName() {
        return studentVariableName;
    }

    public void setStudentVariableName(Student studentVariableName) {
        this.studentVariableName = studentVariableName;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Date getCreateOn() {
        return createOn;
    }

    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }
}
